# Generated by Django 4.1 on 2024-06-07 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_reply"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentLike",
        ),
    ]
