# Generated by Django 4.1 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256, verbose_name="password"),
        ),
    ]
