# Generated by Django 4.1 on 2024-05-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_sex_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Avatar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="birthday"),
        ),
        migrations.AddField(
            model_name="user",
            name="comments_num",
            field=models.IntegerField(default=0, verbose_name="comments_num"),
        ),
        migrations.AddField(
            model_name="user",
            name="followers_num",
            field=models.IntegerField(default=0, verbose_name="followers_num"),
        ),
        migrations.AddField(
            model_name="user",
            name="follows_num",
            field=models.IntegerField(default=0, verbose_name="follows_num"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="user",
            name="liked_num",
            field=models.IntegerField(default=0, verbose_name="liked_num"),
        ),
        migrations.AddField(
            model_name="user",
            name="likes_num",
            field=models.IntegerField(default=0, verbose_name="likes_num"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("uncertain", "Uncertain"),
                ],
                default="uncertain",
                max_length=10,
                verbose_name="gender",
            ),
        ),
    ]
