# Generated by Django 4.1 on 2024-06-08 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
