# Generated by Django 4.1 on 2024-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers_num",
        ),
        migrations.RemoveField(
            model_name="user",
            name="follows_num",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
    ]
