# Generated by Django 4.1 on 2024-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Riddle",
            fields=[
                ("riddle_id", models.AutoField(primary_key=True, serialize=False)),
                ("main_category", models.CharField(max_length=100)),
                ("riddle_text", models.TextField()),
                ("answer", models.TextField()),
                ("difficulty", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
